Implement TH_API functions from the set 1
apaszke/pytorch-dist pull request #48
Opened 2017-01-13 00:46 UTC by 0mp

This branch is **WIP**.

I'll be happy if you could look at the current state of my code and see if I implement those functions correctly.

Related to #47

2017-01-13 21:49 UTC, jytug requested changes
Remember we are in the C++ world now. Return references, not pointers, rename the class methods. Moreover, there are no changes in `master_worker/master/generic/THDTensor.cpp (.h)`. Nor in `master_worker/worker/dispatch/Tensor.cpp`, which are actually your main targets

2017-01-13 21:49 UTC, jytug commented on torch/lib/THD/base/Tensor.hpp
> +  virtual THTensor *THTensor_(newWithSize1d)(long size0_) = 0;
Those ought to be constructors, not tensor methods. On which instance of `THTensor` will you call `newWithSize1d` to create a new one?

2017-01-13 21:49 UTC, jytug commented on torch/lib/THD/base/Tensor.hpp
> +  virtual void THTensor_(narrow)(THTensor *self, THTensor *src, int dimension_, long firstIndex_, long size_) = 0;
We stick to the convention that if a method's return value is `void` or irrelevant, the method should return `*this` (so the return type will be `THTensor&`. Moreover, please change the naming of these methods. `tensor.THTensor_(narrow)` looks silly

2017-01-13 21:49 UTC, jytug commented on torch/lib/THD/base/tensors/generic/THTensor.cpp
> +// template<>
All of these will probably just be a call of an appropriate `TH` function on `tensor`. With some skill, you might be able to `sed` it :-)

2017-01-13 21:49 UTC, jytug commented on torch/lib/THD/master_worker/master/generic/THDTensor.cpp
> +void THDTensor_(setFlag)(THDTensor *self, char flag)
Why so?

2017-01-13 21:49 UTC, jytug commented on torch/lib/THD/master_worker/master/generic/THDTensor.cpp
> +void THDTensor_(clearFlag)(THDTensor *self, char flag)
Why so?

2017-01-13 21:49 UTC, jytug commented on torch/lib/THD/master_worker/worker/Dispatch.cpp
> -#include <unordered_map>
I think we need this here

2017-01-13 21:49 UTC, jytug commented on torch/lib/THD/master_worker/worker/dispatch/Tensor.cpp
> +static void tensorNewWithSize1d(rpc::RPCMessage& raw_message) {
If you choose the `tensorNewWith...` convention over `tensorConstructWith`, please rename all the `construct` functions appropriately, including the `storage` ones. I names them `construct`, as `new` is a keyword, but that's not a problem anymore

2017-01-14 18:55 UTC, 0mp commented on torch/lib/THD/master_worker/master/generic/THDTensor.cpp
> +void THDTensor_(clearFlag)(THDTensor *self, char flag)
It is copied by value so there's no point in making it constant. At least, that's what they thought me in FreeBSD :D

2017-01-15 21:38 UTC, 0mp commented on torch/lib/THD/master_worker/worker/Dispatch.cpp
> -#include <unordered_map>
This library is included twice in this file.

2017-02-27 22:23 UTC, closed without merging