Add Data Channel receive from any source
apaszke/pytorch-dist pull request #52
Opened 2017-01-20 22:43 UTC by VirrageS

2017-01-20 22:47 UTC, apaszke requested changes
Only some minor things, otherwise LGTM

2017-01-20 22:47 UTC, apaszke commented on torch/csrc/distributed/Module.cpp
> +    THPUtils_invalidArguments(args, "isend", 1, "(tensor input, int dst_rank)");
isn't this in `send`?

2017-01-20 22:47 UTC, apaszke commented on torch/distributed/collectives.py
> +def recv(tensor):
I don't think you can do this, it's not C++ :wink:
```python
def recv(tensor, src_rank=None):
    if src_rank is None:
        return torch._C._dist_recv_any_source(tensor)
    return torch._C._dist_recv(tensor, src_rank)
```

2017-01-20 22:47 UTC, apaszke commented on torch/lib/THD/base/channels/DataChannelTCP.cpp
> +    std::unique_ptr<struct pollfd[]> events(new struct pollfd[this->_processes.size()]);
It would be good to cache this somewhere. It's small and constant, so it can be reused.

2017-01-20 22:56 UTC, 0mp approved these changes

2017-01-21 09:46 UTC, VirrageS commented on torch/csrc/distributed/Module.cpp
> +    THPUtils_invalidArguments(args, "isend", 1, "(tensor input, int dst_rank)");
I have changed to `isend`, strange that git/github does not noticed that.

2017-01-21 21:22 UTC, apaszke approved these changes

2017-01-21 21:22 UTC, merged