Implement TH_API functions from the set 4
apaszke/pytorch-dist pull request #58
Opened 2017-03-01 20:03 UTC by VirrageS

Status: **WIP**

Not sure if current implementation of `Generator` and `THDGenerator` is complete and make any sense. These structs are not implemented for `THC` yet.

TODO:
- check if changes compile with CUDA enabled
- add generator for `THC`
- add worker dispatching for generator functions
- style changes

2017-03-02 22:37 UTC, jytug commented
Hey, I've tried to compile your branch on a machine with a proper GPU and CUDA support, but it failed. [Here](http://termbin.com/23ur) is the whole log of `python setup.py build_deps`.
I'll take a look at the code in a while (i.e. tomorrow)

2017-03-02 22:59 UTC, VirrageS commented
I have fixed some of these issues. Not sure if all of them.

2017-03-03 13:02 UTC, jytug commented on torch/lib/THPP/generators/THCGenerator.cpp
> +THCGenerator::THCGenerator(THCState* state))
Won't compile :-)

2017-03-03 13:04 UTC, jytug commented on torch/lib/THPP/generators/THCGenerator.hpp
> +struct THCGenerator : public Generator {
Is it really a template?

2017-03-03 13:25 UTC, jytug requested changes

2017-03-03 13:25 UTC, jytug commented on torch/lib/THPP/generators/THCGenerator.cpp
> +THCGenerator::THCGenerator(THCState* state))
Won't compile ;-)

2017-03-03 13:25 UTC, jytug commented on torch/lib/THPP/generators/THCGenerator.hpp
> +template<typename real>
I don't think it's a template

2017-03-03 13:25 UTC, jytug commented on torch/lib/THPP/generators/THCGenerator.hpp
> +  virtual THCGenerator& seed() override;
It should return `unsigned long`

2017-03-03 13:25 UTC, jytug commented on torch/lib/THPP/generators/THCGenerator.cpp
> +  : generator(THCRandom_getGenerator())
`THCRandom_getGenerator()` is not declared in any `.h` file, so this won't compile either - moreover, the `THCRandom_getGenerator` from `THC` takes a `state` argument

2017-03-03 13:25 UTC, jytug commented on torch/lib/THPP/generators/THCGenerator.cpp
> +  throw std::runtime_error("THCGenerator::copy() not implemented");
Include the `stdexcept` header

2017-03-04 17:06 UTC, apaszke reviewed
Looks very good for the most part. Fix the comments and should be good to go

2017-03-04 17:06 UTC, apaszke commented on torch/lib/THD/master_worker/master/THDRandom.cpp
> +  std::memset(reinterpret_cast<void*>(new_generator), 0, sizeof(new_generator));
Why is that even needed? You're setting the only field below. If you want to ensure this is going to be correct in the future, make the only constructor accept an id.

2017-03-04 17:06 UTC, apaszke commented on torch/lib/THD/master_worker/master/THDRandom.cpp
> +  return receiveValueFromWorker<unsigned long>(THDState::s_current_worker);
What's that value? The used seed?

2017-03-04 17:06 UTC, apaszke commented on torch/lib/THD/master_worker/master/THDRandom.cpp
> +  THDGenerator_free(blank);
I don't get that part. Why is that needed?

2017-03-04 17:06 UTC, apaszke commented on torch/lib/THD/master_worker/master/generic/THDTensorMath.cpp
> +  THDTensor_(uniform)(r_, _generator, 0, 1);
Why is that even needed? Either call resize + uniform, or resize and send a message.

2017-03-04 17:06 UTC, apaszke commented on torch/lib/THD/master_worker/master/generic/THDTensorMath.cpp
> +  THDTensor_(zero)(hist);
I don't think we need that.

2017-03-04 17:06 UTC, apaszke commented on torch/lib/THD/master_worker/master/generic/THDTensorMath.cpp
> +  THDTensor_(normal)(r_, _generator, 0, 1);
That seems unnecessary

2017-03-04 17:06 UTC, apaszke commented on torch/lib/THD/master_worker/master/generic/THDTensorMath.cpp
> +  THDTensor_(zero)(hist);
Remove this.

2017-03-04 17:06 UTC, apaszke commented on torch/lib/THD/master_worker/master/generic/THDTensorRandom.cpp
> +  for (int i = 0; i < n_dist; i++) {
I don't think we need to do this kind of error checking in the master. It's quite unlikely and may have a performance impact.

2017-03-04 17:06 UTC, apaszke commented on torch/lib/THD/master_worker/worker/dispatch/Tensor.cpp
> -static void tensorNeg(rpc::RPCMessage& raw_message) {
Why did you remove these?

2017-03-04 17:06 UTC, apaszke commented on torch/lib/THPP/tensors/generic/THCTensor.cpp
> +  throw std::runtime_error("floating point functions are available only for\
These are byte tensor functions.

2017-03-04 17:10 UTC, VirrageS commented on torch/lib/THD/master_worker/master/THDRandom.cpp
> +  return receiveValueFromWorker<unsigned long>(THDState::s_current_worker);
Yes, `seed` function returns the used seed.

2017-03-04 17:14 UTC, VirrageS commented on torch/lib/THD/master_worker/master/THDRandom.cpp
> +  THDGenerator_free(blank);
It is unnecessary I forgot to delete this. Previously I had more fields in `THDGenerator` struct and this was to clear state of generator I think. From TH:
```
  /* This ensures reseeding resets all of the state (i.e. state for Gaussian numbers) */
```

2017-03-04 17:19 UTC, VirrageS commented on torch/lib/THD/master_worker/worker/dispatch/Tensor.cpp
> -static void tensorNeg(rpc::RPCMessage& raw_message) {
I just moved it to another file: https://github.com/apaszke/pytorch-dist/pull/58/files#diff-c0e7ff130c09526e4236f3b315eecf23R344.

Same with `cinv`.

2017-03-08 17:12 UTC, apaszke approved these changes

2017-03-08 17:12 UTC, merged